.TH "ColorInfo" 3 "Sat Jun 22 2019" "ColrC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ColorInfo \- Holds a known color name and it's \fCBasicValue\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <colr\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "\fBBasicValue\fP \fBcolor\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Holds a known color name and it's \fCBasicValue\fP\&. 

This is used for the \fCcolor_names\fP array\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ColrC from the source code\&.
