.TH "RGB_t" 3 "Sat Jun 22 2019" "ColrC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RGB_t \- Container for RGB values\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <colr\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned char \fBred\fP"
.br
.ti -1c
.RI "unsigned char \fBblue\fP"
.br
.ti -1c
.RI "unsigned char \fBgreen\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Container for RGB values\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ColrC from the source code\&.
